---
cors:
  allow_credentials: true
  allowed_headers:
    - Authorization
    - Content-Type
    - Accept
    - Origin
  allowed_methods:
    - GET
    - DELETE
    - POST
    - OPTIONS
  allowed_origins:
    - apigateawaydomain
http-server:
  address: 0.0.0.0:10000
  idle_timeout: 30s
  timeout: 10s